language: php
php:
  - 7.0
  - 7.1
env:
  global:
    - secure: "A9MgF/c0LCUwmq6LSN2y2U9SxOSgqkorOtag5wUj3I1m2mNPekm3Zr10nWwRXAW5U1F38wBI2rrE6Sat3mzi792/BKMYi9Ls8vREtSRdwphOJLfcaTEvdTJxieVyz4TyXpajYu8sxgAVKb1JluAyS7ci9fht66axC96c/SCFtZQ="
before_install:
  - sudo sh -c "echo 'precedence ::ffff:0:0/96 100' >> /etc/gai.conf"
install:
  # Composer
  - composer self-update
  - composer install -n --prefer-source
  # Database
  - mysql -e 'CREATE DATABASE bluz;'
before_script:
  # Database
  - mysql -uroot bluz < tests/_data/dump.sql
  # Directories
  - mkdir .reports
  - chmod a+w ./tests/cache
  - chmod a+w ./tests/_output
  # Scrutinizer
  - wget https://scrutinizer-ci.com/ocular.phar
script:
  # Check code style
  - php vendor/bin/phpcs
  # Run CodeCeption tests
  - php vendor/bin/codecept run --coverage-xml
after_success:
  # Coveralls
  - php vendor/bin/coveralls -v
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
  # Generate documentation
  - bash .travis.sh
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b84e6a583d6eea87d0eb
      - https://webhooks.gitter.im/e/c4fa557829c5bd992271
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
