language: php
php:
  - 5.6
  - 7.0
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
env:
  global:
    - secure: "j4ecD0iulpiUrRfhSFgFV6v99mgrYbiWFjvCouCzdtHHDYYpf/3/JOdYIn0EzPtjMUaI5FVtjisNpLmcMo+IAEuQAZqB1RAywxBXH41Eh3uuSYEbUFGs0r8d2NsCYWi/h+hGMZozw3ckpch78cniyNc1huMZ5kkbrv3cpMl80m4="
before_install:
  - sudo sh -c "echo 'precedence ::ffff:0:0/96 100' >> /etc/gai.conf"
install:
  # Composer
  - composer self-update
  - composer install -n --prefer-source
  # Database
  - mysql -e 'CREATE DATABASE bluz;'
before_script:
  # Database
  - mysql -uroot bluz < tests/dump.sql
  # Directories
  - mkdir .reports
  - chmod a+w ./tests/cache
script:
  # PHPUnit tests
  - php vendor/bin/phpunit --configuration ./phpunit.xml.dist --coverage-clover=.reports/clover.xml --coverage-xml=.reports/coverage
  # Code style
  - php vendor/bin/phpcs
  # --report=xml --report-file=.reports/phpcs.xml
  # Lines of code
  - php vendor/bin/phploc --log-xml=.reports/phploc.xml src
  # Mess detection
  - php vendor/bin/phpmd ./src xml codesize,unusedcode,naming --reportfile .reports/phpmd.xml || true
  # Duplicate code
  #- php vendor/bin/phpcpd --log-pmd .reports/pmd-cpd.xml src
  # works incorrect with latest PHP versions
  # PHP Depend
  #- php vendor/bin/pdepend --jdepend-xml=.reports/jdepend.xml --jdepend-chart=.reports/dependencies.svg --overview-pyramid=.reports/pyramid.svg  ./src

after_script:
  # Coveralls
  - php vendor/bin/coveralls -v
  # Scrutinizer
  - wget https://scrutinizer-ci.com/ocular.phar
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover .reports/clover.xml; fi;'
  # PHPDocumentor
  - bash .travis.sh
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b84e6a583d6eea87d0eb
      - https://webhooks.gitter.im/e/c4fa557829c5bd992271
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
