language: php
php:
  - 7.0
  - 7.1
env:
  global:
    - secure: "j4ecD0iulpiUrRfhSFgFV6v99mgrYbiWFjvCouCzdtHHDYYpf/3/JOdYIn0EzPtjMUaI5FVtjisNpLmcMo+IAEuQAZqB1RAywxBXH41Eh3uuSYEbUFGs0r8d2NsCYWi/h+hGMZozw3ckpch78cniyNc1huMZ5kkbrv3cpMl80m4="
before_install:
  - sudo sh -c "echo 'precedence ::ffff:0:0/96 100' >> /etc/gai.conf"
install:
  # Composer
  - composer self-update
  - composer install -n --prefer-source
  # Database
  - mysql -e 'CREATE DATABASE bluz;'
before_script:
  # Database
  - mysql -uroot bluz < tests/_data/dump.sql
  # Directories
  - mkdir .reports
  - chmod a+w ./tests/cache
  - chmod a+w ./tests/_output
  # Codeception
  - wget http://codeception.com/codecept.phar
  # Scrutinizer
  - wget https://scrutinizer-ci.com/ocular.phar
script:
  # Code style
  - php vendor/bin/phpcs
  # CodeCeption
  - php codecept.phar run --coverage-xml
after_script:
  # Coveralls
  - php vendor/bin/coveralls -v
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
  # Generate documentation
  - bash .travis.sh
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b84e6a583d6eea87d0eb
      - https://webhooks.gitter.im/e/c4fa557829c5bd992271
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
